# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ip_address',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
