# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_agent',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
